### ISSUE TITLE
Enhancement: Tip Manager Scrolling Accessibility

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#246] opened 2019-09-06 16:40 UTC
### Description
As of now, we have the ability to key through tips with the up and down arrow keys on the keyboard, but do not have a keyboard friendly way to scroll through the text with the internal scrollbar. 

Let's think of a way to accomplish this.

**Comment by driskull** [comment] 2019-10-02 17:02
duplicate of #306

**Closed by driskull** 2019-10-02 17:02 UTC
Labels: enhancement
