### ISSUE TITLE
Bug: CalcitePickList compact mode doesn't render text

### ISSUE THREAD

**Issue by driskull** [Esri/calcite-app-components#781] opened 2020-01-23 06:08 UTC
### Summary

Bug: CalcitePickList compact mode doesn't render text

### Actual Behavior

^

### Expected Behavior

Text and checkbox/radio should be displayed

### Reproduction Steps

1. Go to https://esri.github.io/calcite-app-components/?path=/story/components-calcite-pick-list--basic
2. Toggle compact checkbox
3. Notice that text is no longer displayed and the radio/checkbox isn't either.

**Comment by pr3tori4n** [comment] 2020-02-06 17:30
@driskull please verify.

**Comment by driskull** [comment] 2020-02-06 17:32
@pr3tori4n is the checkbox/radio icon supposed to be gone in `compact`? If so, how does a user know which is selected? cc @asangma 

https://esri.github.io/calcite-app-components/?path=/story/components-calcite-pick-list--basic

**Comment by pr3tori4n** [comment] 2020-02-06 18:13
reassigning to Alan since this is by design I believe.

**Comment by asangma** [comment] 2020-02-11 18:26
Looks good.

**Closed by asangma** 2020-02-11 18:26 UTC
Labels: 4 - verified, bug, p - medium
