### ISSUE TITLE
Bug: Unable to move single calcite-shell-panel to the trailing position

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/calcite-app-components#595] opened 2019-11-27 21:37 UTC
### Summary

We are building a configurable app using calcite-app-components that will have a single side panel. Users may want to configure the app so the single panel appears on either the left or right side of the app.  Based on the shell documentation it seems like we could create a calcite-shell-panel with the slot set to contextual-panel  and the layout set to trailing.  This only works when there are two panels. With just one the panel is always in the leading position. 

### Actual Behavior
The single panel is the leading position even though the trailing layout is set. 

### Expected Behavior

The single panel will display in the trailing position 

### Reproduction Steps

1. Modify the sample code below to point to the location of calcite-app-components. 

```  <!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script type="module" src="./dist/calcite-app/calcite-app.esm.js"></script>
  <script nomodule="" src="./dist/calcite-app/calcite-app.js"></script>
  <link rel="stylesheet" href="./dist/calcite-app/calcite-app.css" />

  <title>Document</title>
</head>

<body>
  <calcite-shell theme="dark">
    <div slot="shell-header">
      <header class="header">
        <h1>Title Text</h1>
      </header>
    </div>
    <!-- also tried contextual panel -->
    <calcite-shell-panel slot="contextual-panel" layout="trailing">Panel</calcite-shell-panel>
  </calcite-shell>
</body>

</html>
 ```

**Comment by driskull** [comment] 2019-12-04 00:02
duplicate of #259

**Closed** 2019-12-04 00:03 UTC
Labels: 0 - new, bug
