### ISSUE TITLE
Bug: Block heading does not have clear focus state

### ISSUE THREAD

**Issue by jimmieego** [Esri/calcite-app-components#253] opened 2019-09-09 23:20 UTC
### Summary

When I set keyboard focus to the block header in Chrome, I only see the bottom focus outline.

### Actual Behavior

![image](https://user-images.githubusercontent.com/5437651/64572760-888d8880-d31d-11e9-99f5-0a6cb51e5a97.png)

### Expected Behavior

Something like this would be good:

![image](https://user-images.githubusercontent.com/5437651/64572796-ace96500-d31d-11e9-9856-8b0a41bc1970.png)

**Comment by asangma** [comment] 2019-09-10 23:55
We can use `outline-offset` until we have a custom focus state re #111.
Any issues with this team?
@driskull @jcfranco @pr3tori4n @kat10140

**Comment by driskull** [comment] 2019-10-02 17:01
duplicate of #308

**Closed by driskull** 2019-10-02 17:01 UTC
Labels: bug
