### ISSUE TITLE
Bug: value-list focus

### ISSUE THREAD

**Issue by kat10140** [Esri/calcite-app-components#986] opened 2020-05-19 22:29 UTC
### Summary
Drag and dropping is acting really finicky with keyboard navigation

### Actual Behavior
Issue # 1 - activating the drag handle and moving the item down and back up to it's original place will then deactivate the item. 
1 - 2 on a similar note, activating the drag and taking the item to the bottom of the list takes the item back to the top and deactivates the drag handle.

![value list bug1](https://user-images.githubusercontent.com/48069902/83292676-5f5ca300-a19f-11ea-9a7b-b3ed468f4e0d.gif)

![value list bug 1-2](https://user-images.githubusercontent.com/48069902/83293039-fe819a80-a19f-11ea-8d13-c1e8b0daa60a.gif)

Issue # 2 - activating the drag handle after selection of an item moves down the item one slot, then the item's drag handle is deactivated and the item is deselected.

![value list bug2](https://user-images.githubusercontent.com/48069902/83292748-7bf8db00-a19f-11ea-98d9-3cff406a3e16.gif)

### Expected Behavior
tabbing and focus to work properly

### Reproduction Steps

1. start up demos in chrome, select drag handle and move down and back. 
2. refresh. select the item, then activate the drag handle and move down once to notice the deselection

**Comment by jcfranco** [comment] 2020-05-28 04:59
@kat10140 I can't repro with the provided steps. Can you add more info?

**Comment by asangma** [comment] 2020-05-28 18:26
I'm also seeing this in Safari.
@jcfranco Note, it mostly seems to be in the drag enabled value-list.

**Comment by jcfranco** [comment] 2020-05-28 19:08
Here's what I've noticed based on my understanding of how the component should work:

### Chrome (81.0.4044.138)

#### Mouse

Immediately dragging an item via the handle works (focus stays on the active item) ✅

#### Keyboard

Tabbing into an item gets focused and selected

  1. Pressing tab focuses the handle ✅
      a. Pressing Space enables drag n' drop mode
      b. Pressing ↕ arrows move item accordingly
      c. After item is moved drag n' drop mode stops ❌
  2. Pressing Tab again focuses the item content ✅, pressing it once more focuses the list's sibling element, if any ✅(reverse order works too)
  3. Pressing ↕ arrows move selection accordingly ✅

### Safari (13.1)

#### Mouse

Immediately dragging an item up or down works ONLY if the handle is focused first (focus stays on the active item) ❌

#### Keyboard

Same as Chrome, except for 1b. where drag n' drop mode stays enabled until Space is pressed again ✅

### Other deets

OSX 10.14.4

**Comment by asangma** [comment] 2020-05-28 22:46
Nice.
Are you able to tab past the first drag-enabled item?

**Comment by asangma** [comment] 2020-05-28 22:49
As a note, there might be some additional keyboard ux that needs reviewing. I'll make a separate issue when I have notes.

**Comment by jcfranco** [comment] 2020-05-28 22:50
> Are you able to tab past the first drag-enabled item?

Only to elements adjacent to the list. This is by design based on https://github.com/Esri/calcite-app-components/issues/873.

**Comment by kat10140** [comment] 2020-05-29 18:32
@jcfranco i have updated the original issue. Happy to screen share and talk this over if you'd like further clarification 😁

**Comment by jcfranco** [comment] 2020-05-29 18:37
@kat10140 Thanks! 

![appreciates](https://user-images.githubusercontent.com/197440/83293462-adbe7180-a1a0-11ea-9e65-1f4d60c7376a.gif)

**Comment by jcfranco** [comment] 2020-06-09 16:07
Installed.

**Comment by jcfranco** [comment] 2020-10-07 00:56
Closing as self-verified.

**Closed by jcfranco** 2020-10-07 00:56 UTC
Labels: 3 - installed, bug
