### ISSUE TITLE
Bug: calcite-panel - footer buttons width not correct

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-app-components#367] opened 2019-10-09 22:27 UTC
### Summary

Once I upgraded to 4.1.0 the footer buttons don't work as expected. 
Done and Cancel have a width of `half` and together should fill the whole panel's width.

![4](https://user-images.githubusercontent.com/44481292/66525100-3a4ce000-eaa9-11e9-8ac2-1af67ec993db.png)

### Reproduction Steps

https://energy.mapsdevext.arcgis.com/apps/mapviewer/index.html

**Comment by driskull** [comment] 2019-10-09 22:41
Very odd but on the mapviewer prototype I see this:

![image](https://user-images.githubusercontent.com/1231455/66525720-35892b80-eaab-11e9-8bb4-54d7691e549f.png)

But on the local build I see this:

![image](https://user-images.githubusercontent.com/1231455/66525741-45a10b00-eaab-11e9-8497-534ad56aa06f.png)


@jcfranco we may need to investigate what's going on with those missing CSS styles.

**Comment by jcfranco** [comment] 2019-10-15 00:13
@driskull Setting the footer slot to 100% fixes the issue, but I'm not sure if this is a regression or not since I see the same issue from the description w/ `calcite-components@beta.10` + `calcite-app-components@v4.0.0` ([pen](https://codepen.io/jcfranco-the-scripter/pen/JjjXrOE)) and `calcite-app-components@v4.1.0` ([pen](https://codepen.io/jcfranco-the-scripter/pen/jOOqGLR)).

@AdelheidF Which dependencies + versions were you using before moving to 4.1.0?

---

> we may need to investigate what's going on with those missing CSS styles.

Based on my testing (4.0.0 - 4.1.1), I think this has always been happening. I looked into the dist folder contents and the string used for to generate the internal style of the panel component looks correct and includes the footer declaration block in its entirety, it just isn't applied at runtime. The issue seems to manifest when using the output from `npm run build`. The `dist` folder produced by `npm start` works as expected. This may be a Stencil bug.

**Comment by AdelheidF** [comment] 2019-10-15 00:18
> Which dependencies + versions were you using before moving to 4.1.0?
@esri/calcite-components@1.0.0-beta.10

"@esri/calcite-app-components": "3.1.0",	    
"@esri/calcite-ui-icons": "^2.4.0",

**Comment by jcfranco** [comment] 2019-10-15 21:25
@AdelheidF I see the same w/ 3.1.0: https://codepen.io/jcfranco-the-scripter/pen/eYYzNdw?editors=1000 Is there something I missed?

**Comment by jcfranco** [comment] 2019-10-15 22:56
I updated the pens based to better match the reported use case, and I noticed the following difference:

**3.1.0**

<img width="365" alt="Screen Shot 2019-10-15 at 3 33 31 PM" src="https://user-images.githubusercontent.com/197440/66874942-855f6b00-ef61-11e9-83a3-d24fd3ec0641.png">

**4.0.0**

<img width="405" alt="Screen Shot 2019-10-15 at 3 33 38 PM" src="https://user-images.githubusercontent.com/197440/66874943-855f6b00-ef61-11e9-8c09-fcb589ee5f9c.png">

@AdelheidF Can you confirm this is the issue at hand?

@driskull I think it has to do with this change: https://github.com/Esri/calcite-app-components/commit/5f58b4c03cb5806d81c2152364e5019016ad70dd#diff-a74c776e239b1c1d09a0767fefe6fcff

**Comment by driskull** [comment] 2019-10-17 05:36
@asangma can you adjust the styling of these buttons as necessary? 

I'm not sure how they are supposed to look.

**Comment by asangma** [comment] 2019-11-04 22:57
I'll hit this when #491 is in.

**Comment by driskull** [comment] 2019-11-04 23:29
491 is in

**Comment by asangma** [comment] 2019-11-05 23:05
@kat10140 Please verfee!

**Comment by asangma** [comment] 2019-11-05 23:08
@driskull Do we need to make a doc update regarding how to use the slot names or is that just common knowledge?

**Comment by driskull** [comment] 2019-11-05 23:09
We should probably have a snippet and documentation on how to use them.

**Comment by kat10140** [comment] 2019-11-05 23:09
Verified

**Comment by asangma** [comment] 2019-11-05 23:09
Thanks @kat10140!
Cool @driskull!

**Closed by kat10140** 2019-11-05 23:09 UTC
Labels: 3 - installed, bug, p - high
