### ISSUE TITLE
Research: FAB keyboard and screenreader usage

### ISSUE THREAD

**Issue by arjavbadjatiya** [Esri/calcite-app-components#868] opened 2020-03-02 19:06 UTC
### Background 
The FAB helps mouse users get to the button quickly when they have dozens of layers in the layer list. However, keyboard users don't seem to be benefitting from the change. You still have to tab through all layers in the list before you can focus on the add layer button. It is not clear if there is a quicker way to get them to the FAB. 

### Desired Outcome 
This needs further exploration. Some ideas:

- Maybe it is higher in the DOM order so keyboard and screenreader users can get to it first when they open the layer panel. (Not sure if that breaks a11y practices for semantic order)
- Maybe there is a way for keyboard/screenreaders to skip the list box holding the layers
- Maybe the button is at the very top (but that has it's own issues)

<img width="238" alt="Screen Shot 2020-03-02 at 10 42 00 AM" src="https://user-images.githubusercontent.com/29237960/75708359-8590a680-5c75-11ea-89ad-45e09a5f7182.png">

CC ISSUE https://github.com/Esri/calcite-components/issues/969

**Comment by driskull** [comment] 2020-05-26 22:58
Seems like we could either...

- Place the fab slot above all the others so that it is tabbed to first.
- Have a hidden anchor for users to skip to the fab? Kinda like the skip navigation a11y solution.

**Comment by arjavbadjatiya** [comment] 2020-05-27 00:18
@driskull Option 1 works since both sighted and non-sighted users should get the option to add layers first.
- Any time a panel with a fab is opened, the fab gets focused on first (unless the panel has a close button in which case the the focus order would be `close->fab->other elements in the panel->next panel or section`).
- When tabbing through the app if you reach an already open panel and the panel happens to have a fab, then again the order should be `close button -> fab->other elements in the panel->next panel or section`.

What do you think?

**Comment by driskull** [comment] 2020-05-27 00:32
I think that makes sense.

**Comment by driskull** [comment] 2020-05-27 15:56
@arjavbadjatiya looking into it. It's not going to be possible to keep it positioned correctly using sticky and have it be in that tab ordering.

I'll see what I can do for option 2.

**Comment by driskull** [comment] 2020-05-27 17:04
Well, option 2 doesn't seem to be working either because of the shadowDom. I'm not sure how we should proceed 🤷

**Comment by arjavbadjatiya** [comment] 2020-05-27 17:39
If we can't do 1 and 2, then we shouldn't use FABs till we have an accessible solution. The point of the FAB is for all users to be able to access it first/quickly/prominently in the panel. For now we should move the "Add layer" and similar fabs to the top of the panels as regular buttons so they'll be visible first and available earlier in the tab order for keyboard/non-sighted users.

**Comment by driskull** [comment] 2020-05-27 17:41
Ok before we remove it I'll assign to @asangma to see if he can come up with a creative way to position it while being first in the dom.

**Comment by driskull** [comment] 2020-06-05 16:25
The problem is that if we place the FAB before the content, the sticky positioning won't work correctly. If we place it after, the tab ordering won't be correct.

I'm not sure we want to mess up the sticky positioning so we need to find some creative way of adjusting the ordering

**Comment by arjavbadjatiya** [comment] 2020-06-05 17:55
Oh if we are thinking of placing it above the content (towards the top of the panel) it will be a regular button, not sticky/FAB.

**Comment by jcfranco** [comment] 2020-06-05 20:47
cc @AdelheidF

**Comment by AdelheidF** [comment] 2020-06-05 23:46
I'm running into a lot of issues with tab orders and calcite components. Not just with the fab button.

E.g. when moving from the close button of that flow-item to the fab button it focuses this section element and I don't know how to tell it not to do that. There's nothing useful about focusing that section, it should just jump over it. Why does it contain a `tabindex` of 0?

![image](https://user-images.githubusercontent.com/44481292/83930117-e2a36900-a74a-11ea-9823-6b1703ffa0be.png)

Maybe it would help if there was a way to set a tabindex like property on components and they place the tabindex within them. Instead of having to call `setFocus()` on each component.

**Comment by driskull** [comment] 2020-06-05 23:51
@AdelheidF that one has a tabIndex of 0 because it may contain scrolling content. We need to ensure that a scrolling area has keyboard access.

**Comment by jcfranco** [comment] 2020-10-07 00:20
Moved to Esri/calcite-components#969

**Closed by jcfranco** 2020-10-07 00:20 UTC
Labels: 1 - assigned, research
